#!/bin/bash

run_help() {
    print_header "Amir CLI Help"
    echo "Usage: $(basename "$0") <command> [args]"
    echo ""
    echo -e "${BOLD}Multimedia:${NC}"
    echo "  video <file> [res] [q]       Compress/Process video (Smart Selection)"
    echo "  video concat <files...>      Concatenate videos in the given order"
    echo "  video cut / trim <file> [opts]  Cut / delete range / extract range (with -s/-e, -d, -x)"
    echo "  video batch [res]            Batch process videos in folder"
    echo "  audio <subcmd> [args]        Audio tools (extract, concat, to-video)"
    echo "  split <file> <mb>            Split audio/video into ~N MB chunks"
    echo "  img <file> [size]            Resize image"
    echo "  info <file>                  Show detailed file info"
    echo "  subtitle <file> [opts]       Generate subtitles (AI Rendering)"
    echo "  video codecs                 Show available codecs"
    
    echo ""
    echo -e "${BOLD}Utilities:${NC}"
    echo "  clip <text|file>             Smart clipboard tool"
    echo "  clean                        Clean system cache/trash"

    echo ""
    echo -e "${BOLD}Research & Trends:${NC}"
    echo "  trend [keyword]              Trending content & research (default: YouTube most viewed)"
    echo "  trend [keyword] --source S   Source: youtube github arxiv reddit producthunt indiehackers"
    echo "  trend [keyword] --lang CODE  Language filter: fa en de ar zh ... (default: any)"
    echo "  trend [keyword] --region CC  Region: IR US GB DE ... (default: global)"
    echo "  trend [keyword] --metric M   Sort by: views likes stars citations comments"
    echo "  trend [keyword] --ideas      Generate AI ideas from collected data"
    echo "  research discover --keywords K [opts]   Find PhD/postdoc supervisors by topic (ArXiv+DBLP)"
    echo "  research professor --professor N [opts] Deep-research a specific professor + draft email"

    echo ""
    echo -e "${BOLD}AI & Productivity:${NC}"
    echo "  router \"<prompt>\" [--model M]  AI gateway: gemini/gemma(free), deepseek, minimax, grok + memory"
    echo "  router audit | cost | models  Cost ledger / dashboard / provider model lists"
    echo "  todo [add/done]              Manage local todo list"
    echo "  scripts [id|list]            Pick & run a saved script (no args = menu; includes"
    echo "                                weather/qr/pass/dashboard/transfer/short/lock/unlock/speed)"
    
    echo ""
    echo -e "${BOLD}System:${NC}"
    echo "  help                         Show this help"
    echo ""
}
